name: release

on:
  push:
  workflow_dispatch:
  # Run at midnight on every friday
  schedule:
    - cron: "0 0 * * FRI"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: hehe
        run: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
            git commit --allow-empty -m "from the action yum"
      - name: Cut release branch and push
        uses: CasperWA/push-protected@v2
        with:
          token: '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'
          branch: main
      #   run: RELEASE_PREFIX=test bash release.sh

