name: release

on:
  push:
  workflow_dispatch:
  # Run at midnight on every friday
  schedule:
    - cron: "0 0 * * FRI"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cut release branch and push
        uses: CasperWA/push-protected@v2
        with:
          token: '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'
          branch: main
      #   run: RELEASE_PREFIX=test bash release.sh

